spring.application.name=emergency-responder
spring.datasource.url=jdbc:h2:mem:medhead;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=false
spring.sql.init.mode=always

spring.datasource.hikari.maximum-pool-size=250
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

server.tomcat.threads.max=400
server.tomcat.max-connections=2000
server.tomcat.accept-count=200

logging.level.org.hibernate.SQL=ERROR
logging.level.org.springframework.web=WARN